[BTAT-9210] New feature switch for dd interrupt
hmrc/vat-summary-frontend pull request #575
Opened 2021-05-06 13:03 UTC by daparkes

2021-05-06 13:32 UTC, daparkes commented
app config pr: https://github.com/hmrc/app-config-production/pull/11191

2021-05-07 07:48 UTC, lewishay requested changes

2021-05-07 07:48 UTC, lewishay commented on conf/application.conf
> +  directDebitInterrupt.enabled = true
Can you please also add the feature switch elements for this to allow it to be toggled via the feature switch test-only page

2021-05-07 07:48 UTC, lewishay commented on app/config/ConfigKeys.scala
> +  val directDebitInterrupt: String = "features.ddInterrupt.enabled"
This String needs to match up with the String you have in `application.conf`

2021-05-07 09:35 UTC, lewishay approved these changes
Approved awaiting clear pipeline

2021-05-07 10:36 UTC, merged