[BTAT-9826] - Added penalties tile and controller logic
hmrc/vat-summary-frontend pull request #639
Opened 2021-11-09 16:01 UTC by BackRowOla

<img width="1560" alt="Screenshot 2021-11-09 at 16 00 31" src="https://user-images.githubusercontent.com/56401572/140959492-af545a07-5c53-44d7-a2a0-d308375ae28b.png">

app-config-base PR:  https://github.com/hmrc/app-config-base/pull/6388

2021-11-10 12:51 UTC, BackRowOla commented
app-config-staging PR: https://github.com/hmrc/app-config-staging/pull/9436

2021-11-10 14:50 UTC, daparkes requested changes

2021-11-10 14:50 UTC, daparkes commented on test/controllers/VatDetailsControllerSpec.scala
>    }
Could you add a test in here for if the user has no penalties

2021-11-10 14:50 UTC, daparkes commented on app/testOnly/controllers/PenaltiesController.scala
> +    println("[Pen Connector][Show] - in the show action!!!!")
Did you mean to leave this in?

2021-11-10 14:54 UTC, BackRowOla commented on app/testOnly/controllers/PenaltiesController.scala
> +    println("[Pen Connector][Show] - in the show action!!!!")
No i didn't 😅

2021-11-10 15:43 UTC, daparkes requested changes
Could you also add the Welsh for the tile? It's in the spreadsheet here https://jira.tools.tax.service.gov.uk/browse/BTAT-9793

2021-11-11 09:24 UTC, daparkes approved these changes

2021-11-11 09:53 UTC, merged