[BTAT-10556] Adding Welsh for WYO page
hmrc/vat-summary-frontend pull request #713
Opened 2022-06-15 14:26 UTC by JoNB7777

2022-06-24 14:13 UTC, lewishay commented on conf/messages.cy
> +whatYouOwe.title = Yr hyn sydd arnoch
Test comment

2022-06-24 15:05 UTC, lewishay requested changes

2022-06-24 15:05 UTC, lewishay commented on conf/messages.cy
> +whatYouOwe.agentTitle = Yr hyn sydd ar eich cleient
Testing Slack integration for PR review comments

2022-07-15 12:42 UTC, paulfirmstone requested changes
As discussed on the call can you amend the name of the Protective Assessment charge title too.

2022-07-20 14:55 UTC, merged