[BTAT-10656] Add AA LPP LPI charge types
hmrc/vat-summary-frontend pull request #767
Opened 2022-08-16 10:15 UTC by daparkes

https://github.com/hmrc/financial-transactions/pull/82

2022-08-18 15:03 UTC, daparkes commented
One of the charge breakdown view models had a `description` method, which we only need for the charge rows and not the breakdowns, so I got rid of it

2022-08-19 09:41 UTC, paulfirmstone requested changes

2022-08-19 09:41 UTC, paulfirmstone commented on test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
> +      val model = exampleModel.copy(chargeType = VatOA2ndLPPLPI)
This is testing the wrong charge type.

2022-08-19 09:41 UTC, paulfirmstone commented on app/models/payments/ChargeType.scala
> +    VatPA2ndLPPLPI,
These charges also need to be in interestChargeTypes in order to generate the correct breakdown screen.

2022-08-19 11:56 UTC, merged