[BTAT-10762] - Added in VAT AA Quarterly Instal LPI, VAT AA Monthly Instal LPI, VAT AA Return Charge 1st LPP, VAT AA Return Charge 2nd LPP
hmrc/vat-summary-frontend pull request #770
Opened 2022-08-22 10:16 UTC by william-hatzar

2022-08-22 10:17 UTC, william-hatzar commented
This can be reviewed but I'm waiting on Linds, to let me know if the charge type that I have included is the correct wording or not. I presume it is

2022-08-22 10:22 UTC, william-hatzar commented
Financial transactions PR - https://github.com/hmrc/financial-transactions/pull/85

2022-08-23 14:49 UTC, daparkes requested changes

2022-08-23 14:49 UTC, daparkes commented on app/views/templates/payments/PaymentMessageHelper.scala
> +    Some("chargeType.for")
I think these all need to be `chargeType.forPeriod`, so that they all read 'for period XXXX' in their descriptions

2022-08-24 10:11 UTC, merged