DL-13381 - added webchat link
hmrc/vat-summary-frontend pull request #933
Opened 2024-03-28 19:17 UTC by derickdamoah

2024-03-28 19:20 UTC, derickdamoah commented
review config PRs
https://github.com/hmrc/app-config-qa/pull/21938
https://github.com/hmrc/app-config-production/pull/21710
https://github.com/hmrc/app-config-staging/pull/14927

2024-04-02 16:46 UTC, peckover requested changes

2024-04-02 16:46 UTC, peckover commented on app/views/certificate/VatCertificate.scala.html
> +        <br>
Can you use the GDS classes to add padding please? <br> can make it difficult for screen readers
https://design-system.service.gov.uk/styles/spacing/

2024-04-02 16:46 UTC, peckover commented on app/views/certificate/VatCertificate.scala.html
> +            <a class="govuk-link" href="https://www.tax.service.gov.uk/ask-hmrc/chat/vat-online?ds" target="_blank" id="webchatLink-id">@messages("webchat.askHMRC")</a>
Can you make it so the link doesn't hand off to the production url locally and in the test environments please. i.e. create the handoff in app config and use the services host and port to get the base url

2024-04-03 11:02 UTC, peckover approved these changes

2024-04-03 11:02 UTC, merged